const mails = [
    {
        'from': 'Pablo-Diego-José-Francisco fff.ffff@example.com',
        'to': ['qqq.qq@example.com'],
        'subject': '[info:888] ABC EQUIPMENT COMPANY',
        'isAttached': false,
        'date': 'Tue Dec 31 2019 09:00:00 GMT+0900 (Japan Standard Time)',
        'body': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam vestibulum sagittis eros a imperdiet. Nullam venenatis eros in elit posuere faucibus id id erat. Duis nunc mauris, eleifend at orci pellentesque, imperdiet varius arcu. Aliquam pretium, est et auctor vestibulum, quam orci efficitur nibh, sed hendrerit ante mauris a magna. Integer eu erat turpis. Suspendisse potenti. Sed a ante mauris. Morbi malesuada, justo vel suscipit porta, leo nibh tempor elit, eget pretium justo odio quis nulla. Vivamus lacus massa, fringilla sed purus sit amet, volutpat viverra neque. Nullam scelerisque accumsan sapien, sed tristique quam auctor varius. Vestibulum porta augue enim. Quisque iaculis purus vel turpis dictum varius. Cras id lobortis lectus.',
    },
    {
        'from': 'aaa@example.com',
        'to': ['zzz.zzz@example.com'],
        'subject': '[ HR-888 ] Notice of official announcement',
        'isAttached': false,
        'date': 'Mon Dec 23 2019 10:50:00 GMT+0900 (Japan Standard Time)',
        'body': 'A Lorem Ipsum egy egyszerû szövegrészlete, szövegutánzata a betûszedõ és nyomdaiparnak. A Lorem Ipsum az 1500-as évek óta standard szövegrészletként szolgált az iparban; mikor egy ismeretlen nyomdász összeállította a betûkészletét és egy példa-könyvet vagy szöveget nyomott papírra, ezt használta. Nem csak 5 évszázadot élt túl, de az elektronikus betûkészleteknél is változatlanul megmaradt. Az 1960-as években népszerûsítették a Lorem Ipsum részleteket magukbafoglaló Letraset lapokkal, és legutóbb softwarekkel mint például az Aldus Pagemaker.',
    },
    {
        'from': 'bbb.bbbb@example.com',
        'to': ['yyy@example.com'],
        'subject': '[web:333] "Web Contact"',
        'isAttached': false,
        'date': 'Mon Dec 23 2019 10:45:00 GMT+0900 (Japan Standard Time)',
        'body': 'Lorem Ipsum är en utfyllnadstext från tryck- och förlagsindustrin. Lorem ipsum har varit standard ända sedan 1500-talet, när en okänd boksättare tog att antal bokstäver och blandade dem för att göra ett provexemplar av en bok. Lorem ipsum har inte bara överlevt fem århundraden, utan även övergången till elektronisk typografi utan större förändringar. Det blev allmänt känt på 1960-talet i samband med lanseringen av Letraset-ark med avsnitt av Lorem Ipsum, och senare med mjukvaror som Aldus PageMaker.',
    },
    {
        'from': 'bbb.bbbb@example.com',
        'to': ['yyy@example.com', 'vvv.vvv@example.com'],
        'subject': '[web:333] "Web Contact"',
        'isAttached': true,
        'date': 'Mon Dec 23 2019 10:40:00 GMT+0900 (Japan Standard Time)',
        'body': 'Proin hendrerit sapien eget mauris pellentesque, a tincidunt lorem convallis. Nulla nec libero in neque tincidunt hendrerit vel nec magna. Morbi sit amet consectetur eros, in sagittis dui. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi dolor nisl, interdum at mauris sit amet, sodales dignissim justo. Maecenas quis lacus eu elit pretium ultricies. Curabitur vestibulum at nibh ac mollis. Praesent laoreet lectus sed dui sodales imperdiet. Morbi pellentesque faucibus eros sit amet dapibus. Donec ac orci lacus. Nunc sed elementum sem. Donec mi diam, pharetra sed gravida sed, facilisis nec nisl. Ut condimentum cursus tortor, sit amet fermentum dui viverra sit amet. Pellentesque eget metus pretium, consectetur tellus eget, porttitor nibh. Sed ac nisl in dolor rutrum mollis. In bibendum tincidunt eros, sed sodales arcu mollis ac.',
    },
    {
        'from': 'ddd.dddd@example.com',
        'to': ['vvv.vvv@example.com', 'yyy@example.com'],
        'subject': '[HR-887(Revised: Office Expansion Project Team)] Notice of off Lorem ipsum dolor sit amet.',
        'isAttached': true,
        'date': 'Sun Dec 22 2019 09:00:00 GMT+0900 (Japan Standard Time)',
        'body': 'Lorem Ipsum jest tekstem stosowanym jako przykładowy wypełniacz w przemyśle poligraficznym. Został po raz pierwszy użyty w XV w. przez nieznanego drukarza do wypełnienia tekstem próbnej książki. Pięć wieków później zaczął być używany przemyśle elektronicznym, pozostając praktycznie niezmienionym. Spopularyzował się w latach 60. XX w. wraz z publikacją arkuszy Letrasetu, zawierających fragmenty Lorem Ipsum, a ostatnio z zawierającym różne wersje Lorem Ipsum oprogramowaniem przeznaczonym do realizacji druków na komputerach osobistych, jak Aldus PageMaker',
    },
    {
        'from': 'eee@example.com',
        'to': ['sss@example.com', 'sss@example.com', 'sss@example.com'],
        'subject': '[Github] Logout page',
        'isAttached': false,
        'date': 'Sun Dec 22 2019 09:00:00 GMT+0900 (Japan Standard Time)',
        'body': 'Lorem Ipsum è un testo segnaposto utilizzato nel settore della tipografia e della stampa. Lorem Ipsum è considerato il testo segnaposto standard sin dal sedicesimo secolo, quando un anonimo tipografo prese una cassetta di caratteri e li assemblò per preparare un testo campione. È sopravvissuto non solo a più di cinque secoli, ma anche al passaggio alla videoimpaginazione, pervenendoci sostanzialmente inalterato. Fu reso popolare, negli anni ’60, con la diffusione dei fogli di caratteri trasferibili “Letraset”, che contenevano passaggi del Lorem Ipsum, e più recentemente da software di impaginazione come Aldus PageMaker, che includeva versioni del Lorem Ipsum.',
    },
    {
        'from': 'fff.ffff@example.com',
        'to': ['qqq.qq@example.com'],
        'subject': '[dev]Postfix 3.1.12 / 3.2.9 / 3.3.4 / 3.4.5',
        'isAttached': false,
        'date': 'Sun Dec 22 2019 09:00:00 GMT+0900 (Japan Standard Time)',
        'body': 'Lorem Ipsum छपाई और अक्षर योजन उद्योग का एक साधारण डमी पाठ है. Lorem Ipsum सन १५०० के बाद से अभी तक इस उद्योग का मानक डमी पाठ मन गया, जब एक अज्ञात मुद्रक ने नमूना लेकर एक नमूना किताब बनाई. यह न केवल पाँच सदियों से जीवित रहा बल्कि इसने इलेक्ट्रॉनिक मीडिया में छलांग लगाने के बाद भी मूलतः अपरिवर्तित रहा. यह 1960 के दशक में Letraset Lorem Ipsum अंश युक्त पत्र के रिलीज के साथ लोकप्रिय हुआ, और हाल ही में Aldus PageMaker Lorem Ipsum के संस्करणों सहित तरह डेस्कटॉप प्रकाशन सॉफ्टवेयर के साथ अधिक प्रचलित हुआ.',
    },

    {
        'from': 'ggg@example.com',
        'to': ['ppp.qq@example.com'],
        'subject': 'Re: [Github] Brush-up on loading animation',
        'isAttached': false,
        'date': 'Sun Dec 22 2019 09:00:00 GMT+0900 (Japan Standard Time)',
        'body': 'Lorem Ipsum, dizgi ve baskı endüstrisinde kullanılan mıgır metinlerdir. Lorem Ipsum, adı bilinmeyen bir matbaacının bir hurufat numune kitabı oluşturmak üzere bir yazı galerisini alarak karıştırdığı 1500\'lerden beri endüstri standardı sahte metinler olarak kullanılmıştır. Beşyüz yıl boyunca varlığını sürdürmekle kalmamış, aynı zamanda pek değişmeden elektronik dizgiye de sıçramıştır. 1960\'larda Lorem Ipsum pasajları da içeren Letraset yapraklarının yayınlanması ile ve yakın zamanda Aldus PageMaker gibi Lorem Ipsum sürümleri içeren masaüstü yayıncılık yazılımları ile popüler olmuştur.',
    },
    {
        'from': 'hhh.hhh@example.com',
        'to': ['ooo.ooo@example.com'],
        'subject': 'Workplace Summary for sample, Inc.: Jun 2 - Jun 9',
        'isAttached': true,
        'date': 'Sun Dec 22 2019 09:00:00 GMT+0900 (Japan Standard Time)',
        'body': 'Lorem Ipsum chỉ đơn giản là một đoạn văn bản giả, được dùng vào việc trình bày và dàn trang phục vụ cho in ấn. Lorem Ipsum đã được sử dụng như một văn bản chuẩn cho ngành công nghiệp in ấn từ những năm 1500, khi một họa sĩ vô danh ghép nhiều đoạn văn bản với nhau để tạo thành một bản mẫu văn bản. Đoạn văn bản này không những đã tồn tại năm thế kỉ, mà khi được áp dụng vào tin học văn phòng, nội dung của nó vẫn không hề bị thay đổi. Nó đã được phổ biến trong những năm 1960 nhờ việc bán những bản giấy Letraset in những đoạn Lorem Ipsum, và gần đây hơn, được sử dụng trong các ứng dụng dàn trang, như Aldus PageMaker.',
    },
    {
        'from': 'iii@example.com',
        'to': ['nnn@example.com'],
        'subject': 'I love you',
        'isAttached': false,
        'date': 'Tue Dec 31 2019 09:00:00 GMT+0900 (Japan Standard Time)',
        'body': 'Praesent non libero nisi. Ut et ante ex. Vestibulum quam massa, volutpat sed purus ut, ullamcorper tristique mauris. Mauris at mattis enim. Quisque tincidunt, ligula at tristique posuere, nunc diam mattis augue, vel facilisis magna turpis et metus. Pellentesque sed nulla id dui porttitor consequat vitae in orci. Integer id libero dictum risus ultrices fermentum. Nunc at varius mauris, sed porttitor nisi. Ut blandit ut massa nec venenatis.',
    },
];

export default mails;